In [16]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Redal\OneDrive\Desktop\Travel euro\FashionDataset.csv")
print(df)


df.columns

       Unnamed: 0    BrandName  \
0               0         life
1               1         only
2               2      fratini
3               3  zink london
4               4         life
...           ...          ...
30753          21    swarovski
30754          22          Nan
30755          23       jewelz
30756          24      estelle
30757          25      estelle

                                                 Deatils  \
0      solid cotton blend collar neck womens a-line d...
1      polyester peter pan collar womens blouson dres...
2      solid polyester blend wide neck womens regular...
3      stripes polyester sweetheart neck womens dress...
4      regular fit regular length denim womens jeans ...
...                                                  ...
30753            crystal stylish womens rodhium earrings
30754                                                Nan
30755                 ethnic gold plated jhumki earrings
30756  womens gold plated double line fancy white and...
30757  womens gold plated bridge designer mangalsutra...

                                         Sizes       MRP SellPrice Discount  \
0      Size:Large,Medium,Small,X-Large,X-Small  Rs\n1699       849  50% off
1                             Size:34,36,38,40  Rs\n3499      2449  30% off
2                  Size:Large,X-Large,XX-Large  Rs\n1199       599  50% off
3              Size:Large,Medium,Small,X-Large  Rs\n2299      1379  40% off
4                       Size:26,28,30,32,34,36  Rs\n1699       849  50% off
...                                        ...       ...       ...      ...
30753                                      Nan       Nan      8950      Nan
30754                                      Nan       Nan       Nan      Nan
30755                                      Nan  Rs\n1839       643  65% off
30756                                      Nan       Nan      2799      Nan
30757                                      Nan       Nan      1899      Nan

                Category
0      Westernwear-Women
1      Westernwear-Women
2      Westernwear-Women
3      Westernwear-Women
4      Westernwear-Women
...                  ...
30753    Jewellery-Women
30754    Jewellery-Women
30755    Jewellery-Women
30756    Jewellery-Women
30757    Jewellery-Women

[30758 rows x 8 columns]

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='object')

In [22]:
print(df.head(20))

      BrandName                                            Deatils  \
0          life  solid cotton blend collar neck womens a-line d...
1          only  polyester peter pan collar womens blouson dres...
2       fratini  solid polyester blend wide neck womens regular...
3   zink london  stripes polyester sweetheart neck womens dress...
4          life  regular fit regular length denim womens jeans ...
5         kraus  wide ankle length cotton womens jeans - light ...
6          life  printed cotton blend collared womens regular d...
7       fratini  embroidered wide neck polyester womens regular...
8          rare  floral polyester v neck womens flared dress - ...
9          rare  checks cotton boat neck womens regular top - b...
10         life  solid square neck cotton womens regular dress ...
11         life  regular fit regular length denim womens jeans ...
12         life  printed blended round neck womens shift dress ...
13         life   printed jersey round neck womens t-shirt - black
14         life        printed crepe square neck womens top - blue
15         life       solid cotton collar neck womens shirt - pink
16         life  solid cotton lycra round neck womens t-shirt -...
17         life    printed cotton collar neck womens shirt - white
18   van heusen   solid cotton v neck womens formal shirt - maroon
19         life  regular fit regular length denim womens jeans ...

                                      Sizes       MRP SellPrice Discount  \
0   Size:Large,Medium,Small,X-Large,X-Small  Rs\n1699       849  50% off
1                          Size:34,36,38,40  Rs\n3499      2449  30% off
2               Size:Large,X-Large,XX-Large  Rs\n1199       599  50% off
3           Size:Large,Medium,Small,X-Large  Rs\n2299      1379  40% off
4                    Size:26,28,30,32,34,36  Rs\n1699       849  50% off
5                       Size:26,28,30,32,34  Rs\n1795      1615  10% off
6   Size:Large,Medium,Small,X-Large,X-Small  Rs\n1299       649  50% off
7                             Size:XX-Large  Rs\n1299       649  50% off
8           Size:Large,Medium,Small,X-Large  Rs\n2099       839  60% off
9                 Size:Medium,Small,X-Large  Rs\n1499       599  60% off
10  Size:Large,Medium,Small,X-Large,X-Small  Rs\n1499       749  50% off
11                   Size:26,28,30,32,34,36   Rs\n999       499  50% off
12  Size:Large,Medium,Small,X-Large,X-Small  Rs\n1499       749  50% off
13  Size:Large,Medium,Small,X-Large,X-Small   Rs\n599       299  50% off
14  Size:Large,Medium,Small,X-Large,X-Small   Rs\n999       499  50% off
15  Size:Large,Medium,Small,X-Large,X-Small  Rs\n1199       599  50% off
16          Size:Large,Medium,Small,X-Small   Rs\n599       299  50% off
17  Size:Large,Medium,Small,X-Large,X-Small  Rs\n1299       649  50% off
18                 Size:Large,Small,X-Small  Rs\n1999       799  60% off
19                   Size:26,28,30,32,34,36  Rs\n1999       999  50% off

             Category
0   Westernwear-Women
1   Westernwear-Women
2   Westernwear-Women
3   Westernwear-Women
4   Westernwear-Women
5   Westernwear-Women
6   Westernwear-Women
7   Westernwear-Women
8   Westernwear-Women
9   Westernwear-Women
10  Westernwear-Women
11  Westernwear-Women
12  Westernwear-Women
13  Westernwear-Women
14  Westernwear-Women
15  Westernwear-Women
16  Westernwear-Women
17  Westernwear-Women
18  Westernwear-Women
19  Westernwear-Women

In [23]:

df

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30753,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [24]:
df.columns

Index(['BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='object')

In [48]:

df.rename(columns= {"Deatils" : "Details"})
df.columns

Index(['BrandName', 'Details', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(2827)

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30752,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
30753,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30755,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [54]:
df.reset_index()

,index,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...,...
27926,30752,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
27927,30753,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
27928,30755,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
27929,30756,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
27930,30757,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [58]:
df1= df.reset_index().drop(columns= "index")

In [59]:
df1

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
27926,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
27927,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
27928,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
27929,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
27930,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [61]:
df1.isna().sum()

BrandName    0
Details      0
Sizes        0
MRP          0
SellPrice    0
Discount     0
Category     0
dtype: int64

In [62]:
df1.dropna(inplace=True)

In [65]:
df1.isna().sum()

BrandName    0
Details      0
Sizes        0
MRP          0
SellPrice    0
Discount     0
Category     0
dtype: int64

In [71]:
df1["BrandName"].apply(lambda x: x.capitalize())

0                      Life
1                      Only
2                   Fratini
3               Zink london
4                      Life
                ...
27926    Shaya by caratlane
27927             Swarovski
27928                Jewelz
27929               Estelle
27930               Estelle
Name: BrandName, Length: 27931, dtype: object

In [72]:
df1["Details"].apply(lambda x: x.capitalize())

0        Solid cotton blend collar neck womens a-line d...
1        Polyester peter pan collar womens blouson dres...
2        Solid polyester blend wide neck womens regular...
3        Stripes polyester sweetheart neck womens dress...
4        Regular fit regular length denim womens jeans ...
                               ...
27926                 The wing woman clover charm necklace
27927              Crystal stylish womens rodhium earrings
27928                   Ethnic gold plated jhumki earrings
27929    Womens gold plated double line fancy white and...
27930    Womens gold plated bridge designer mangalsutra...
Name: Details, Length: 27931, dtype: object

In [73]:
df1["Sizes"][27929]

'Nan'

In [76]:
df1["Sizes"] = df1["Sizes"].replace("Nan", "NA VALUED")

In [77]:
df1

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
27926,shaya by caratlane,the wing woman clover charm necklace,NA VALUED,Nan,1250,Nan,Jewellery-Women
27927,swarovski,crystal stylish womens rodhium earrings,NA VALUED,Nan,8950,Nan,Jewellery-Women
27928,jewelz,ethnic gold plated jhumki earrings,NA VALUED,Rs\n1839,643,65% off,Jewellery-Women
27929,estelle,womens gold plated double line fancy white and...,NA VALUED,Nan,2799,Nan,Jewellery-Women
27930,estelle,womens gold plated bridge designer mangalsutra...,NA VALUED,Nan,1899,Nan,Jewellery-Women

In [80]:
df1[df1["Sizes"] != "NA VALUED"]

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
24344,swiss eagle,womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
24731,lawman watches,womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
25791,lawman watches,womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women
26028,miu miu,eau de parfum - 50 ml,Size:Error Size,Nan,6100,Nan,Fragrance-Women
26078,miu miu,eau de parfum - 30 ml,Size:Error Size,Nan,4400,Nan,Fragrance-Women

In [81]:
df1["Discount]"] = df1["Discount"].replace("Nan", "No Discosunt")

In [82]:
df1

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category,Discount]
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women,50% off
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women,30% off
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women,50% off
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women,40% off
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women,50% off
...,...,...,...,...,...,...,...,...
27926,shaya by caratlane,the wing woman clover charm necklace,NA VALUED,Nan,1250,Nan,Jewellery-Women,No Discosunt
27927,swarovski,crystal stylish womens rodhium earrings,NA VALUED,Nan,8950,Nan,Jewellery-Women,No Discosunt
27928,jewelz,ethnic gold plated jhumki earrings,NA VALUED,Rs\n1839,643,65% off,Jewellery-Women,65% off
27929,estelle,womens gold plated double line fancy white and...,NA VALUED,Nan,2799,Nan,Jewellery-Women,No Discosunt
27930,estelle,womens gold plated bridge designer mangalsutra...,NA VALUED,Nan,1899,Nan,Jewellery-Women,No Discosunt

In [83]:
df1["Sizes"]= df1["Sizes"].replace("NA VALUED", "Size:Error Size")

In [84]:
df1

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category,Discount]
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women,50% off
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women,30% off
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women,50% off
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women,40% off
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women,50% off
...,...,...,...,...,...,...,...,...
27926,shaya by caratlane,the wing woman clover charm necklace,Size:Error Size,Nan,1250,Nan,Jewellery-Women,No Discosunt
27927,swarovski,crystal stylish womens rodhium earrings,Size:Error Size,Nan,8950,Nan,Jewellery-Women,No Discosunt
27928,jewelz,ethnic gold plated jhumki earrings,Size:Error Size,Rs\n1839,643,65% off,Jewellery-Women,65% off
27929,estelle,womens gold plated double line fancy white and...,Size:Error Size,Nan,2799,Nan,Jewellery-Women,No Discosunt
27930,estelle,womens gold plated bridge designer mangalsutra...,Size:Error Size,Nan,1899,Nan,Jewellery-Women,No Discosunt

In [85]:
df1.to_excel("Cleaned_data.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

In [86]:
df1.to_csv("FashionDataset_Cleaned.csv", index= False)

In [88]:
df1.to_excel("Cleaned_FashionDataset.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

In [89]:
pd.read_csv("FashionDataset_Cleaned.csv")

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category,Discount]
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women,50% off
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women,30% off
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women,50% off
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women,40% off
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women,50% off
...,...,...,...,...,...,...,...,...
27926,shaya by caratlane,the wing woman clover charm necklace,Size:Error Size,Nan,1250,Nan,Jewellery-Women,No Discosunt
27927,swarovski,crystal stylish womens rodhium earrings,Size:Error Size,Nan,8950,Nan,Jewellery-Women,No Discosunt
27928,jewelz,ethnic gold plated jhumki earrings,Size:Error Size,Rs\n1839,643,65% off,Jewellery-Women,65% off
27929,estelle,womens gold plated double line fancy white and...,Size:Error Size,Nan,2799,Nan,Jewellery-Women,No Discosunt
27930,estelle,womens gold plated bridge designer mangalsutra...,Size:Error Size,Nan,1899,Nan,Jewellery-Women,No Discosunt